# Generated by Django 3.0.3 on 2020-02-21 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryChangeLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=500)),
                ('quantity', models.IntegerField()),
                ('change_type', models.CharField(max_length=500)),
                ('change_by', models.CharField(max_length=500)),
                ('change_date', models.DateTimeField()),
                ('comment', models.CharField(blank=True, default=None, max_length=500, null=True)),
            ],
        ),
    ]
